<?php

return [
    'columns' => [
        'id' => 'Mã',
        'name' => 'Tên',
        'email' => 'Email',
        'email_verified_at' => 'Thời gian xác thực email',
        'ma_dang_nhap' => 'Mã đăng nhập',
        'password' => 'Mật khẩu',
        'remember_token' => 'Mã ghi nhớ',
        'token' => 'Mã xác thực',
        'ip_address' => 'Địa chỉ IP',
        'user_agent' => 'Trình duyệt',
        'last_activity' => 'Hoạt động gần nhất',
        'guard_name' => 'Cổng xác thực',
        'is_active' => 'Trạng thái',
        'ma_khoa' => 'Mã khoa',
        'ten_khoa' => 'Tên khoa',
        'ma_lop' => 'Mã lớp',
        'ten_lop' => 'Tên lớp',
        'nien_khoa' => 'Niên khóa',
        'ma_sinh_vien' => 'Mã sinh viên',
        'ho_ten' => 'Họ tên',
        'ngay_sinh' => 'Ngày sinh',
        'gioi_tinh' => 'Giới tính',
        'so_dien_thoai' => 'Số điện thoại',
        'dia_chi' => 'Địa chỉ',
        'trang_thai' => 'Trạng thái',
        'ten_nam_hoc' => 'Tên năm học',
        'ngay_bat_dau' => 'Ngày bắt đầu',
        'ngay_ket_thuc' => 'Ngày kết thúc',
        'ten_hoc_ky' => 'Tên học kỳ',
        'thu_tu' => 'Thứ tự',
        'han_tu_danh_gia' => 'Hạn tự đánh giá',
        'han_gvcn_duyet' => 'Hạn GVCN duyệt',
        'han_hoi_dong_duyet' => 'Hạn hội đồng duyệt',
        'ngay_cong_bo' => 'Ngày công bố',
        'ma_tieu_chi' => 'Mã tiêu chí',
        'ten_tieu_chi' => 'Tên tiêu chí',
        'mo_ta' => 'Mô tả',
        'diem_toi_da' => 'Điểm tối đa',
        'ten_muc' => 'Tên mức',
        'ten_file' => 'Tên tệp',
        'duong_dan' => 'Đường dẫn',
        'loai_file' => 'Loại tệp',
        'ghi_chu_duyet' => 'Ghi chú duyệt',
        'ma_hoat_dong' => 'Mã hoạt động',
        'ten_hoat_dong' => 'Tên hoạt động',
        'loai_hoat_dong' => 'Loại hoạt động',
        'thoi_gian_bat_dau' => 'Thời gian bắt đầu',
        'thoi_gian_ket_thuc' => 'Thời gian kết thúc',
        'so_luong_toi_da' => 'Số lượng tối đa',
        'diem_cong' => 'Điểm cộng',
        'auto_cong_diem' => 'Tự động cộng điểm',
        'is_bat_buoc' => 'Bắt buộc',
        'tieu_de' => 'Tiêu đề',
        'noi_dung' => 'Nội dung',
        'ghi_chu' => 'Ghi chú',
        'ly_do' => 'Lý do',
        'metadata' => 'Dữ liệu bổ sung',
        'loai' => 'Loại',
        'doi_tuong' => 'Đối tượng',
        'published_at' => 'Ngày đăng',
        'het_han_at' => 'Hết hạn',
        'hanh_dong' => 'Hành động',
        'created_at' => 'Ngày tạo',
        'updated_at' => 'Ngày cập nhật',
        'deleted_at' => 'Ngày xóa',
        'file_name' => 'Tên tệp sao lưu',
        'path' => 'Đường dẫn tệp',
        'file_path' => 'Đường dẫn tệp',
        'disk' => 'Ổ lưu trữ',
        'size' => 'Dung lượng',
        'file_size' => 'Dung lượng',
        'status' => 'Trạng thái',
        'message' => 'Thông báo',
        'created_by' => 'Người tạo',
        'sinh_vien_id' => 'Sinh viên',
        'phieu_danh_gia_id' => 'Phiếu đánh giá',
        'chi_tiet_danh_gia_id' => 'Chi tiết đánh giá',
        'muc_tieu_chi_id' => 'Mức tiêu chí',
        'hoat_dong_id' => 'Hoạt động',
        'dang_ky_hoat_dong_id' => 'Đăng ký hoạt động',
        'checked_in_by' => 'Người điểm danh',
        'checked_in_at' => 'Thời gian điểm danh',
        'phuong_thuc' => 'Phương thức',
        'tong_diem' => 'Tổng điểm',
        'diem_hoat_dong' => 'Điểm hoạt động',
        'diem_tu_cham' => 'Điểm tự chấm',
        'diem_gvcn' => 'Điểm GVCN',
        'diem_hoi_dong' => 'Điểm hội đồng',
        'diem_cuoi' => 'Điểm cuối cùng',
        'diem_cu' => 'Điểm cũ',
        'diem_moi' => 'Điểm mới',
        'xep_loai' => 'Xếp loại',
        'nhan_xet_sinh_vien' => 'Nhận xét sinh viên',
        'nhan_xet_gvcn' => 'Nhận xét GVCN',
        'nhan_xet_hoi_dong' => 'Nhận xét hội đồng',
        'submitted_at' => 'Thời gian nộp',
        'reviewed_at' => 'Thời gian duyệt',
        'approved_at' => 'Thời gian xác nhận',
        'locked_at' => 'Thời gian khóa',
        'cong_bo_at' => 'Thời gian công bố',
        'nguon' => 'Nguồn',
        'qr_token' => 'Mã QR',
        'user_id' => 'Tài khoản',
        'lop_id' => 'Lớp',
        'khoa_id' => 'Khoa',
        'gvcn_id' => 'GVCN/Cố vấn',
        'nam_hoc_id' => 'Năm học',
        'hoc_ky_id' => 'Học kỳ',
        'tieu_chi_id' => 'Tiêu chí',
        'uploaded_by' => 'Người tải lên',
        'reviewed_by' => 'Người duyệt',
        'approved_by' => 'Người xác nhận',
        'locked_by' => 'Người khóa',
    ],

    'statuses' => [
        'dang_hoc' => 'Đang học',
        'bao_luu' => 'Bảo lưu',
        'da_tot_nghiep' => 'Đã tốt nghiệp',
        'draft' => 'Nháp',
        'submitted' => 'Đã nộp',
        'reviewed' => 'GVCN đã duyệt',
        'approved' => 'Đã duyệt',
        'locked' => 'Đã khóa',
        'pending' => 'Chờ duyệt',
        'rejected' => 'Từ chối',
        'attended' => 'Đã điểm danh',
        'open' => 'Đang mở',
        'closed' => 'Đã đóng',
        'cancelled' => 'Đã hủy',
        'final' => 'Cuối cùng',
        'success' => 'Thành công',
        'failed' => 'Thất bại',
    ],

    'booleans' => [
        0 => 'Không',
        1 => 'Có',
    ],

    'active' => [
        0 => 'Ngưng hoạt động',
        1 => 'Đang hoạt động',
    ],

    'guards' => [
        'web' => 'Web',
    ],

    'roles' => [
        'admin' => 'Quản trị viên',
        'sinh_vien' => 'Sinh viên',
        'gvcn' => 'GVCN/Cố vấn',
        'can_bo_doan_hoi' => 'Cán bộ Đoàn - Hội',
        'hoi_dong_khoa' => 'Hội đồng/Khoa',
    ],

    'permissions' => [
        'self evaluate' => 'Tự đánh giá',
        'review class forms' => 'Duyệt phiếu lớp phụ trách',
        'manage activities' => 'Quản lý hoạt động',
        'approve final scores' => 'Xác nhận điểm cuối cùng',
        'export reports' => 'Xuất báo cáo',
    ],

    'messages' => [
        'profile-updated' => 'Đã cập nhật hồ sơ.',
        'password-updated' => 'Đã cập nhật mật khẩu.',
        'verification-link-sent' => 'Liên kết xác thực mới đã được gửi.',
    ],
];
